name = "uiblockhub"
compatibility_date = "2025-03-20"

[build]
command = "npm install && npm run build"  # Your build command
pages_build_output_dir = "dist"           # Your output directory (e.g., "dist", "build")